#!/usr/bin/env python

import argparse, threading, sys, queue
import backend

def main():
    parser = argparse.ArgumentParser(
            description="Create Epub documents from fanfiction online.",
            formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("-c", "--connections", default=2, type=int,
        help="maximum number of simultaneous connections (default 2)")
    parser.add_argument("-f", "--file",
     help="filename for the resulting Epub\n(default <author> - <title>.epub)")
    parser.add_argument("URL", help="URL of the first chapter")
    parser.add_argument("--version", action="version",
            version="%(prog)s 1.0\n2014 Aleksi Blinnikka")
    args = parser.parse_args()

    print("Downloading story from {}".format(args.URL))
    progress_queue = backend.get_queue()
    creator_thread = threading.Thread(target=backend.create_document,
            args=(args.URL, args.connections, args.file))
    creator_thread.start()
    while True:
        try:
            progress = progress_queue.get(timeout=1)
        except queue.Empty:
            pass
        else:
            print(progress)
            progress_queue.task_done()
        if not creator_thread.is_alive():
            break
    print("Done!")

if __name__ == "__main__":
    main()

